const australiaData = [
  {
    id: 1,
    name: "Diploma in Computing",
    school: "The University of Melbourne",
    country: "Australia",
    degree: "Undergraduate Diploma",
    duration: "2 years",
    tuition: "AUD$50,272",
    url: "https://study.unimelb.edu.au/find/courses/undergraduate/diploma-in-computing/how-to-apply/",
  },
  {
    id: 2,
    name: "Diploma in LAW",
    school: "University of melbourne",
    country: "Australia",
    degree: "Undergraduate Diploma",
    duration: "2 years",
    tuition: "AUD$22,656",
    url: "https://study.unimelb.edu.au/find/?s=law",
  },
  {
    id: 3,
    name: "Bachelor of science",
    school: "University of melbourne",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "\nAUD$145,808-$184,432",
    url: "https://study.unimelb.edu.au/",
  },
  {
    id: 4,
    name: "Bachelor of science",
    school: "University of melbourne",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "AUD$14,808-$184,432",
    url: "https://study.unimelb.edu.au/find/study-areas/nursing/",
  },
  {
    id: 5,
    name: "Master of Laws",
    school: "University of melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "AUD$46,656",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-laws/",
  },
  {
    id: 6,
    name: "Juris Doctor",
    school: "University of melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "\nAUD$44,480",
    url: "https://study.unimelb.edu.au/find/courses/graduate/juris-doctor/",
  },
  {
    id: 7,
    name: "Detecting Flaws in Reasoning",
    school: "University of melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "$1490 AUD (inc GST)",
    url: "https://study.unimelb.edu.au/find/microcredentials/detecting-flaws-in-reasoning/",
  },
  {
    id: 8,
    name: "Graduate Diploma in LAW",
    school: "University of melbourne",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "\nAUD$23,328",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-laws/",
  },
  {
    id: 9,
    name: "Master of commercial Law",
    school: "University of melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$46,656 ",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-commercial-law/",
  },
  {
    id: 10,
    name: "Master of construction Law",
    school: "University of melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$46,656",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-construction-law/",
  },
  {
    id: 11,
    name: "Master of Environmental Law",
    school: "University of melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$46,656 ",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-environmental-law/",
  },
  {
    id: 12,
    name: "Master of Private Law",
    school: "University of melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$46,656",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-private-law/",
  },
  {
    id: 13,
    name: "Doctor of Philosophy Law",
    school: "University of melbourne",
    country: "Australia",
    degree: "Doctorate",
    duration: "2 years",
    tuition: "\nAUD$43,104",
    url: "https://study.unimelb.edu.au/find/courses/graduate/doctor-of-philosophy-law/",
  },
  {
    id: 14,
    name: "Graduate Diploma in Asian LAW",
    school: "University of melbourne",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "\nAUD$23,328",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-asian-law/VV",
  },
  {
    id: 15,
    name: "Master of Architectural Engineering",
    school: "University of melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$46,304",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-architectural-engineering/",
  },
  {
    id: 16,
    name: "Master of Biomedical Engineering(MSc)",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "AUD$50,272",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-biomedical-engineering/",
  },
  {
    id: 17,
    name: "Master of Chemical Engineering(MSc)",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "AUD$50,272",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-chemical-engineering/",
  },
  {
    id: 18,
    name: "Doctor of Philosophy Engineering and IT(PHD)",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Doctorate",
    duration: "2 years",
    tuition: "AUD$51,648",
    url: "https://study.unimelb.edu.au/find/courses/graduate/doctor-of-philosophy-engineering-and-it/",
  },
  {
    id: 19,
    name: "Master of Philosophy Engineering and IT(MPhil)",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "AUD$51,648",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-philosophy-engineering-and-it/",
  },
  {
    id: 20,
    name: "Master of Civil Engineering(MSc)",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "AUD$50,272",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-civil-engineering/",
  },
  {
    id: 21,
    name: "Master of Electrical Engineering",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$158,482",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-electrical-engineering/",
  },
  {
    id: 22,
    name: "Master of Engineering Structures",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$50,272",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-engineering-structures/",
  },
  {
    id: 23,
    name: "Master of Engineering Management",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$50,272",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-engineering-management/",
  },
  {
    id: 24,
    name: "Master of Industrial Engineering",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$103,057",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-industrial-engineering/",
  },
  {
    id: 25,
    name: "Master of Mechanical Engineering",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-mechanical-engineering/",
  },
  {
    id: 26,
    name: "Master Environmental Engineering",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "AUD$158,482",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-environmental-engineering/",
  },
  {
    id: 27,
    name: "Bachelor of Science",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "",
    url: "https://study.unimelb.edu.au/find/courses/undergraduate/bachelor-of-science/",
  },
  {
    id: 28,
    name: "Bachelor of Biomedicine",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "\nAUD$135,504-$157,184",
    url: "https://study.unimelb.edu.au/find/courses/undergraduate/bachelor-of-biomedicine/",
  },
  {
    id: 29,
    name: "Master of Nursing Science",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$71,176",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-nursing-science/",
  },
  {
    id: 30,
    name: "Graduate Certificate in Cancer Nursing",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "AUD$11,744",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-cancer-nursing/",
  },
  {
    id: 31,
    name: "Master of Advanced Nursing practice",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$35,392",
    url: "",
  },
  {
    id: 32,
    name: "Specialist certificate in cancer Nursing",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "\nAUD$5,872",
    url: "https://study.unimelb.edu.au/find/courses/graduate/specialist-certificate-in-cancer-nursing/",
  },
  {
    id: 33,
    name: "Transition to Critical Care Nursing",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: " AUD $275 inc. GST",
    url: "https://study.unimelb.edu.au/find/short-courses/transition-to-critical-care-nursing/",
  },
  {
    id: 34,
    name: "Graduate Certificate in Critical Care Nursing ",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "\nAUD$11,744",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-critical-care-nursing/",
  },
  {
    id: 35,
    name: "Graduate Certificate in Nursing practice paediatrics",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "\nAUD$17,776",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-nursing-practice-paediatrics/",
  },
  {
    id: 36,
    name: "Graduate Certificate in Primary Care Nursing",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-primary-care-nursing/",
  },
  {
    id: 37,
    name: "Graduate Diploma in Primary Care Nursing",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-primary-care-nursing/",
  },
  {
    id: 38,
    name: "Specialist certificate in critical Nursing",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "",
    url: "https://study.unimelb.edu.au/find/courses/graduate/specialist-certificate-in-critical-care-nursing/",
  },
  {
    id: 39,
    name: "Urgent Care Emergency Nursing Essentials",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: " AUD $480 (incl. GST)",
    url: "https://study.unimelb.edu.au/find/short-courses/urgent-care-emergency-nursing-essentials/",
  },
  {
    id: 40,
    name: "Graduate Certificate in Critical care Nursing Emergency",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "\nAUD$11,472",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-critical-care-nursing-emergency/",
  },
  {
    id: 41,
    name: "Graduate diploma in Mental Heaith Nursing Practice",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "AUD$23,488",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-mental-health-nursing-practice/",
  },
  {
    id: 42,
    name: "Master of Advanced Nursing practice(Nurse Practitioner)",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-advanced-nursing-practice-nurse-practitioner/",
  },
  {
    id: 43,
    name: "Graduate Certificate in Nursing practice paediatrics intensive care",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "\nAUD$17,776",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-nursing-practice-paediatric-intensive-care/",
  },
  {
    id: 44,
    name: "Master of Advanced Nursing Practice(Master of Public Health)",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-advanced-nursing-practice-master-of-public-health/",
  },
  {
    id: 45,
    name: "Transition to Mental Health Nursing and Allied Heaith ",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "AUD $475 excl. GST",
    url: "https://study.unimelb.edu.au/find/short-courses/transition-to-mental-health-nursing-and-allied-health/",
  },
  {
    id: 46,
    name: "Master of Computer Science",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$103,057",
    url: "https://study.unimelb.edu.au/find/courses/graduate/master-of-computer-science/",
  },
  {
    id: 47,
    name: "Graduate Certificate in Computer Science ",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "\nAUD$25,136",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-computer-science/",
  },
  {
    id: 48,
    name: "Graduate Diploma In Computer Science",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "AUD$50,272\n",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-computer-science/",
  },
  {
    id: 49,
    name: "Graduate Diploma in Data Science",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "\nAUD$48,832",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-data-science/",
  },
  {
    id: 50,
    name: "Graduate Diploma in Science Advanced",
    school: "University of Melbourne",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "\nAUD$48,128",
    url: "https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-science-advanced/",
  },
  {
    id: 51,
    name: "Msc Computer Science",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-computer-science.html",
  },
  {
    id: 52,
    name: "Msc of data science",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-data-science0.html",
  },
  {
    id: 53,
    name: "Graduate Diploma In Computer Science",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-diploma-in-computer-science.html",
  },
  {
    id: 54,
    name: "Graduate Certificate in Computer Science ",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-certificate-in-computer-science.html",
  },
  {
    id: 55,
    name: "Master of Cybersecurity(MSc)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-cybersecurity.html",
  },
  {
    id: 56,
    name: "Graduate Diploma in Cybersecurity",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-diploma-in-cybersecurity.html",
  },
  {
    id: 57,
    name: "Graduate Certificate in Cybersecurity",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "A$26,500",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-certificate-in-cybersecurity.html",
  },
  {
    id: 58,
    name: "Master of Engineering (Software Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-software.html",
  },
  {
    id: 59,
    name: "Graduate Diploma in Engineering",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "A$39,750",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-diploma-in-engineering.html",
  },
  {
    id: 60,
    name: "Graduate Certificate in Engineering",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "A$26,500",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-certificate-in-engineering.html",
  },
  {
    id: 61,
    name: "Master of Engineering (Civil Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-civil-engineering.html",
  },
  {
    id: 62,
    name: "Master of Engineering (Structural Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-structural-engineering.html",
  },
  {
    id: 63,
    name: "Master of Engineering (Fluids Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-fluids-engineering.html",
  },
  {
    id: 64,
    name: "Master of Engineering (Electrical Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-electrical-engineering.html",
  },
  {
    id: 65,
    name: "Master of Engineering (Power Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-power-engineering.html",
  },
  {
    id: 66,
    name: "Master of Engineering (Telecommunications Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-telecommunications-engineering.html",
  },
  {
    id: 67,
    name: "Master of Engineering (Biomedical Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-biomedical-engineering.html",
  },
  {
    id: 68,
    name: "Master of Engineering (Geomechanical Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-geomechanical-engineering.html",
  },
  {
    id: 69,
    name: "Master of Professional Engineering(Power)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-power.html",
  },
  {
    id: 70,
    name: "Master of Professional Engineering(Civil)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-civil.html",
  },
  {
    id: 71,
    name: "Bachelor of Engineering Honour\\Bachelor of Project Management",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-engineering-honours-bachelor-of-project-management.html",
  },
  {
    id: 72,
    name: "Master of Professional Engineering(Biomedical)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-biomedical.html",
  },
  {
    id: 73,
    name: "Master Of Professional Engineering (software)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-software.html",
  },
  {
    id: 74,
    name: "Master of Professional Engineering(Aerospace)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-aerospace.html",
  },
  {
    id: 75,
    name: "Master of Professional Engineering (Electrical)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-electrical.html",
  },
  {
    id: 76,
    name: "Master of Professional Engineering(Mechanical)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-mechanical.html",
  },
  {
    id: 77,
    name: "Master of Professional Engineering(Structural)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-structural.html",
  },
  {
    id: 78,
    name: "Master of Professional Engineering(Accelerated)(Intelligent Information Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-intelligent-information-e",
  },
  {
    id: 79,
    name: "Master of Professional Engineering Geomechanical",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-geomechanical.html",
  },
  {
    id: 80,
    name: "Master of Professional Engineering(Accelerated)(Power)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-power.html",
  },
  {
    id: 81,
    name: "Bachelor of Engineering Honours(Software Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-engineering-honours-software-engineering1.html",
  },
  {
    id: 82,
    name: "Bachelor of Engineering Honours (Biomedical) and Bachelor of Science (Medical Science)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-engineering-honours-biomedical-and-bachelor-of-science-",
  },
  {
    id: 83,
    name: "Master of Engineering (Sustainability and Environmental Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-sustainability-and-environmental-engineering.html",
  },
  {
    id: 84,
    name: "Bachelor of Project Management (Honours)\n\n \n",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-project-management-honours.html",
  },
  {
    id: 85,
    name: "Graduate Certificate in Engineering",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-certificate-in-engineering.html",
  },
  {
    id: 86,
    name: "Bachelor of Engineering Honours (Civil) and Bachelor of Design in Architecture",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-engineering-honours-civil-and-bachelor-of-design-in",
  },
  {
    id: 87,
    name: "Master of Engineering (Automation and Manufacturing Systems)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-automation-and-manufacturing-systems.html",
  },
  {
    id: 88,
    name: "Bachelor of Engineering Honours (Biomedical) and Bachelor of Science (Health)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-engineering-honours-biomedical-and-bachelor-of-science-",
  },
  {
    id: 89,
    name: "Master of Engineering (Intelligent Information Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-intelligent-information-engineering.html",
  },
  {
    id: 90,
    name: "Master of Professional Engineering (Accelerated) (Civil)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-civil.html",
  },
  {
    id: 91,
    name: "Doctor of Philosophy (Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Doctorate",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pr/doctor-of-philosophy-engineering.html",
  },
  {
    id: 92,
    name: "Graduate Diploma in Engineering",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/graduate-diploma-in-engineering.html",
  },
  {
    id: 93,
    name: "Master of Professional Engineering (Accelerated) (Fluids)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-fluids.html",
  },
  {
    id: 94,
    name: "Bachelor of Engineering Honours (Biomedical Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-engineering-honours-biomedical-engineering2.html",
  },
  {
    id: 95,
    name: "Bachelor of Engineering Honours (Civil Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/bachelor-of-engineering-honours-civil-engineering2.html",
  },
  {
    id: 96,
    name: "Master of Professional Engineering (Accelerated) (Software)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-software.html",
  },
  {
    id: 97,
    name: "Master of Professional Engineering (Accelerated) (Aerospace)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-aerospace.html",
  },
  {
    id: 98,
    name: "Engineering Undergraduate Cross-Institutional",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/engineering-undergraduate-cross-institutional.html",
  },
  {
    id: 99,
    name: "Master of Professional Engineering (Accelerated) (Electrical)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-electrical.html",
  },
  {
    id: 100,
    name: "Master of Professional Engineering (Accelerated) (Mechanical)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-mechanical.html",
  },
  {
    id: 101,
    name: "Engineering Undergraduate Non-Degree",
    school: "University of Sydney",
    country: "Australia",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/uc/engineering-undergraduate-non-degree.html",
  },
  {
    id: 102,
    name: "Master of Engineering (Chemical and Biomolecular Engineering)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-engineering-chemical-and-biomolecular-engineering.html",
  },
  {
    id: 103,
    name: "Master of Professional Engineering (Telecommunications)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-telecommunications.html",
  },
  {
    id: 104,
    name: "Master of Professional Engineering (Accelerated) (Structural)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-structural.html",
  },
  {
    id: 105,
    name: "Engineering Postgraduate Cross-Institutional\nShare\n \n",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Diploma",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/engineering-postgraduate-cross-institutional.html",
  },
  {
    id: 106,
    name: "Master of Professional Engineering (Accelerated) (Biomedical)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-biomedical0.html",
  },
  {
    id: 107,
    name: "Master of Professional Engineering (Accelerated) (Geomechanical)",
    school: "University of Sydney",
    country: "Australia",
    degree: "Masters",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/master-of-professional-engineering-accelerated-geomechanical.html",
  },
  {
    id: 108,
    name: "Engineering Postgraduate Non-Degree",
    school: "University of Sydney",
    country: "Australia",
    degree: "Postgraduate Certificate",
    duration: "2 years",
    tuition: "A$53,000",
    url: "https://www.sydney.edu.au/courses/courses/pc/engineering-postgraduate-non-degree.html",
  },
];

export default australiaData;
