// course data for Netherlands
const netherlandsData = [
  {
    id: 1,
    name: "BA American Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/american-studies/#int",
  },
  {
    id: 2,
    name: "BA Art History",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/art-history/#int",
  },
  {
    id: 3,
    name: "BA Arts, Culture and Media",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/arts-culture-and-media/#int",
  },
  {
    id: 4,
    name: "BA Communication and Information Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/communication-and-information-studies/#int",
  },
  {
    id: 5,
    name: "BA English Language and Culture",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/english-language-and-culture/#int",
  },
  {
    id: 6,
    name: "BA European Languages and Culture",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/european-languages-and-cultures/",
  },
  {
    id: 7,
    name: "BA History",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/history/#int",
  },
  {
    id: 8,
    name: "BA International Relations and International Organization",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/international-relations-and-international-organization/#int",
  },
  {
    id: 9,
    name: "BA Media Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/media-studies/#int",
  },
  {
    id: 10,
    name: "BA Minority & Multilingualism",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/minorities-multilingualism/#int",
  },
  {
    id: 11,
    name: "BSc Data Science and Society",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/data-science-and-society/",
  },
  {
    id: 12,
    name: "BSc Econometrics and Operations Research",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/econometrics-and-operations-research/#int",
  },
  {
    id: 13,
    name: "BSc Economics and Business Economics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/economics-and-business-economics/",
  },
  {
    id: 14,
    name: "BSc International Business",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/international-business/#int",
  },
  {
    id: 15,
    name: "BSC Applied Mathematics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/applied-mathematics/#int",
  },
  {
    id: 16,
    name: "BSc Applied Physics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/applied-physics/",
  },
  {
    id: 17,
    name: "BSc Artificial Intelligence",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/artificial-intelligence/#int",
  },
  {
    id: 18,
    name: "BSc Astronomy",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/astronomy/#int",
  },
  {
    id: 19,
    name: "BSc Biology",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/biology/",
  },
  {
    id: 20,
    name: "BSc Biomedical Engineering",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/biomedical-engineering/#int",
  },
  {
    id: 21,
    name: "BSc Chemical Engineering",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/chemical-engineering/#int",
  },
  {
    id: 22,
    name: "BSc Chemistry",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/chemistry/#int",
  },
  {
    id: 23,
    name: "BSc Computing Science",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/computing-science/#int",
  },
  {
    id: 24,
    name: "BSc Industrial Engineering and Management",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/industrial-engineering-and-management/#int",
  },
  {
    id: 25,
    name: "BSc Life Science and Technology",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/life-science-and-technology/#int",
  },
  {
    id: 26,
    name: "BSc Mathematics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/mathematics/#int",
  },
  {
    id: 27,
    name: "BSc Pharmacy",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/pharmacy/#int",
  },
  {
    id: 28,
    name: "BSc Physics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 16,500",
    url: "https://www.rug.nl/bachelors/physics/",
  },
  {
    id: 29,
    name: "BSc Medicine",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 32,000",
    url: "https://www.rug.nl/bachelors/medicine/",
  },
  {
    id: 30,
    name: "BSc Human Geography and Planning",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/human-geography-and-planning/",
  },
  {
    id: 31,
    name: "BSc Spatial Planning and Design",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/spatial-planning-and-design/#int",
  },
  {
    id: 32,
    name: "BSc Psychology",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/psychology-en/#int",
  },
  {
    id: 33,
    name: "BSc Philosophy of a Specific Discipline",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/philosophy-of-a-specific-discipline/",
  },
  {
    id: 34,
    name: "LLB International and European Law",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/international-and-european-law/",
  },
  {
    id: 35,
    name: "BA Religious Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/religious-studies/#int",
  },
  {
    id: 36,
    name: "BSc Liberal Arts and Sciences",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/liberal-arts-and-sciences/#int",
  },
  {
    id: 37,
    name: "BSc Global Responsibility and Leadership",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "€ 11,200",
    url: "https://www.rug.nl/bachelors/global-responsibility-and-leadership/#int",
  },
  {
    id: 38,
    name: "MA Archeology(Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.19",
    url: "https://www.rug.nl/masters/archaeology-research/",
  },
  {
    id: 39,
    name: "MA Arts & Culture",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.18",
    url: "https://www.rug.nl/masters/arts-and-culture/",
  },
  {
    id: 40,
    name: "MA Arts, Cognition and criticism",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.17",
    url: "https://www.rug.nl/masters/arts-cognition-and-criticism/",
  },
  {
    id: 41,
    name: "MA Arts, Policy and cultural Entrepreneurship",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.16",
    url: "https://www.rug.nl/masters/arts-policy-and-cultural-entrepreneurship/",
  },
  {
    id: 42,
    name: "MA Art History & Curatorial Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.15",
    url: "https://www.rug.nl/masters/art-history/",
  },
  {
    id: 43,
    name: "MA Film and Contemporary Audiovisual Media",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.14",
    url: "https://www.rug.nl/masters/film-and-contemporary-audiovisual-media/",
  },
  {
    id: 44,
    name: "MA Arts & Culture (History of Architecture and Town planning)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.13",
    url: "https://www.rug.nl/masters/history-of-architecture-and-town-planning/",
  },
  {
    id: 45,
    name: "MA Arts & Culture (Music, Theatre and Performance Studies)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.12",
    url: "https://www.rug.nl/masters/music-theatre-and-performance-studies/",
  },
  {
    id: 46,
    name: "MA Arts & Culture(Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.11",
    url: "https://www.rug.nl/masters/arts-culture-research/",
  },
  {
    id: 47,
    name: "MA Arts & Culture (Cultural Leadership)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.10",
    url: "https://www.rug.nl/masters/cultural-leadership-research/",
  },
  {
    id: 48,
    name: "MA Arts & Culture (Media and Literary Studies)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.09",
    url: "https://www.rug.nl/masters/arts-media-and-literary-studies-research/",
  },
  {
    id: 49,
    name: "MA Classics & Ancient Civilizations",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.08",
    url: "https://www.rug.nl/masters/classics-ancient-civilizations/",
  },
  {
    id: 50,
    name: "MA Classics & Ancient Civilizations(Ancient History)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.07",
    url: "https://www.rug.nl/masters/ancient-history/",
  },
  {
    id: 51,
    name: "MA Classics & Ancient Civilizations(Classics)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.06",
    url: "https://www.rug.nl/masters/classics/",
  },
  {
    id: 52,
    name: "MA Communications & Information Studies(Digital Humanities)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.05",
    url: "https://www.rug.nl/masters/digital-humanities/",
  },
  {
    id: 53,
    name: "MSc Information Science",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.04",
    url: "https://www.rug.nl/masters/information-science/",
  },
  {
    id: 54,
    name: "MA European Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.03",
    url: "https://www.rug.nl/masters/euroculture-em/",
  },
  {
    id: 55,
    name: "MA History",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.02",
    url: "https://www.rug.nl/masters/history/",
  },
  {
    id: 56,
    name: "MA History & Heritage Consultancy",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.01",
    url: "https://www.rug.nl/masters/history-and-heritage-consultancy/",
  },
  {
    id: 57,
    name: "MA History(Unsustainable societies: past present, future)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/unsustainable-societies-past-present-and-future/",
  },
  {
    id: 58,
    name: "MA History(Politics, Organisations and Learning Histories)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/politics-organizations-and-learning-histories/",
  },
  {
    id: 59,
    name: "MA History(Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/history-research/",
  },
  {
    id: 60,
    name: "MA International Relations",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/international-relations-60-ec/",
  },
  {
    id: 61,
    name: "MA International Relations(East Asia Studies)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/east-asian-studies/",
  },
  {
    id: 62,
    name: "MA International Relations(European Politics in a Global Perspective)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/european-politics-in-a-global-perspective/",
  },
  {
    id: 63,
    name: "MA International Relations(Geopolitics & connectivity)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/geopolitics-connectivity/",
  },
  {
    id: 64,
    name: "MA International Relations(International relations and International Organisations)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/international-relations-and-international-organization/",
  },
  {
    id: 65,
    name: "MA International Relations(International Political Economy)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/international-political-economy/",
  },
  {
    id: 66,
    name: "MA International Humanitarian action",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 12,000.00 ",
    url: "https://www.rug.nl/masters/international-humanitarian-action-120-ec/",
  },
  {
    id: 67,
    name: "MA Modern History and International Relations",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/modern-history-and-international-relations-research/",
  },
  {
    id: 68,
    name: "MA Linguistics(Applied Linguistics)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/applied-linguistics-tefl/",
  },
  {
    id: 69,
    name: "MA Theoretical and Emperical Linguistics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/theoretical-and-empirical-linguistics/",
  },
  {
    id: 70,
    name: "MA Linguistics(Multilingualism)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/multilingualism/",
  },
  {
    id: 71,
    name: "MA Clinical Linguistics(Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 9,000.00 ",
    url: "https://www.rug.nl/masters/clinical-linguistics-emcl-research/",
  },
  {
    id: 72,
    name: "MA Linguistics(Language and Cognition)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/language-and-cognition-research/",
  },
  {
    id: 73,
    name: "MA/MSc Linguistics(Language and Communications Technology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 8,500.00 ",
    url: "https://www.rug.nl/masters/language-and-communication-technologies-double-degree-programme-research/",
  },
  {
    id: 74,
    name: "MA Literary Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/literary-studies/",
  },
  {
    id: 75,
    name: "MA Literary Studies(Literature and Culture)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/english-literature-and-culture/",
  },
  {
    id: 76,
    name: "MA Literary Studies(European Literatures and Interculturality)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/european-literatures-and-interculturality/",
  },
  {
    id: 77,
    name: "MA Literary Studies(Writing, Editing, Mediating)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/writing-editing-and-mediating/",
  },
  {
    id: 78,
    name: "MA Media Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/media-studies/",
  },
  {
    id: 79,
    name: "MA Media Studies(Datafication and Digital Literacy)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/datafication-and-digital-literacy/",
  },
  {
    id: 80,
    name: "MA Media Studies(Journalism)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/journalism-english-taught/",
  },
  {
    id: 81,
    name: "MA Media Studies(Media Creation and Innovation)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/media-creation-and-innovation/",
  },
  {
    id: 82,
    name: "MA Media Studies(Social Media and Society)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/social-media-and-society/",
  },
  {
    id: 83,
    name: "MA Middle Eastern Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/middle-eastern-studies/",
  },
  {
    id: 84,
    name: "MA North American Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: " € 16,000.00 ",
    url: "https://www.rug.nl/masters/north-american-studies/",
  },
  {
    id: 85,
    name: "MSc Behavioural and Social Sciences (Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/behavioural-and-social-sciences-research/",
  },
  {
    id: 86,
    name: "MSc Educational Sciences (Learning in Interaction)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/learning-in-interaction/",
  },
  {
    id: 87,
    name: "MSc Pedagogical Sciences (Deafblindness)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/deafblindness/",
  },
  {
    id: 88,
    name: "MSc Pedagogical Sciences (Ethics of Education: philosophy, history and law)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ethics-of-education-philosophy-history-and-law/",
  },
  {
    id: 89,
    name: "MSc Pedagogical Sciences (Youth 0-21, Society and Policy)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/youth-0-21-society-and-policy/",
  },
  {
    id: 90,
    name: "MSc Psychology",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/psychology/",
  },
  {
    id: 91,
    name: "MSc Psychology (Work, Organizational, and Personnel Psychology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/work-organizational-and-personnel-psychology/",
  },
  {
    id: 92,
    name: "MSc Psychology (Applied Social Psychology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/applied-social-psychology/",
  },
  {
    id: 93,
    name: "MSc Psychology (Clinical Neuropsychology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/clinical-neuropsychology/",
  },
  {
    id: 94,
    name: "MSc Psychology (DDM Sustainability and Environmental Psychology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-sustainability-and-environmental-psychology/",
  },
  {
    id: 95,
    name: "MSc Psychology (Applied cognitive Neuroscience)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/applied-cognitive-neuroscience/",
  },
  {
    id: 96,
    name: "MSc Psychology (Clinical Forensic Psychology and Victimology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/clinical-forensic-psychology-and-victimology/",
  },
  {
    id: 97,
    name: "MSc Psychology (Environmental Psychology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/environmental-psychology/",
  },
  {
    id: 98,
    name: "MSc Psychology (Theory and History of Psychology)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/theory-and-history-of-psychology/",
  },
  {
    id: 99,
    name: "MSc Psychology (Talent Development and Creativity)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/talent-development-and-creativity/",
  },
  {
    id: 100,
    name: "MSc Accountancy and Controlling",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/accountancy-and-controlling/",
  },
  {
    id: 101,
    name: "MSc Accounting and Controlling (DDM Chinese Economy and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 102,
    name: "MSc Business Administration",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/business-administration/",
  },
  {
    id: 103,
    name: "MSc Business Administration (Change Management)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/change-management/",
  },
  {
    id: 104,
    name: "MSc Business Administration (Management Accounting and Control)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/management-accounting-and-control/",
  },
  {
    id: 105,
    name: "MSc Business Administration (Small Business and Entrepreneurship)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/small-business-and-entrepreneurship/",
  },
  {
    id: 106,
    name: "MSc Business Administration (Strategic Innovation Management)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/strategic-innovation-management/",
  },
  {
    id: 107,
    name: "MSc Business Administration (Health)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/business-administration-health/",
  },
  {
    id: 108,
    name: "MA/MSc Econometrics, Operations Research, and Actuarial Studies",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/econometrics-operations-research-and-actuarial-studies/",
  },
  {
    id: 109,
    name: "MA/MSc Econometrics, Operations Research, and Actuarial Studies (DDM Chinese Economy and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 110,
    name: "MA/MSc Economic Development and Globilization",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/economic-development-and-globalization/",
  },
  {
    id: 111,
    name: "MA/MSc Economic Development and Globilization (DDM Chinese Economy and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 112,
    name: "MA/MSc Economic Development and Globilization (DDM Central-East European Economies)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-central-east-european-economies/",
  },
  {
    id: 113,
    name: "MSc Economic Development and Globilization (DDM International Development Economics)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-international-development-economics/",
  },
  {
    id: 114,
    name: "MSc Economic Development and Globilization (DDM Economic Development and Growth MEDEG)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-economic-development-and-growth-medeg/",
  },
  {
    id: 115,
    name: "MSc Economics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/economics/",
  },
  {
    id: 116,
    name: "MSc Economics (DDM Chinese Economy and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 117,
    name: "MSc Economics (DDM Economics and Economic Analysis)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-economics-and-economic-analysis/",
  },
  {
    id: 118,
    name: "MSc Finance",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/finance/",
  },
  {
    id: 119,
    name: "MSc Finance (DDM Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-finance/",
  },
  {
    id: 120,
    name: "MSc Finance (DDM Chinese Economy and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 121,
    name: "MSc Human Resource Management",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/human-resource-management/",
  },
  {
    id: 122,
    name: "MSc International Business and Management",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/international-business-and-management/",
  },
  {
    id: 123,
    name: "MSc International Business and Management (DDM Advanced International Business Management and Marketing)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-advanced-international-business-management-and-marketing/",
  },
  {
    id: 124,
    name: "MSc International Business and Management (DDM Chinese Economy and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 125,
    name: "MSc International Financial Management",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/international-financial-management/",
  },
  {
    id: 126,
    name: "MSc International Financial Management (DDM Chinese Economy and Finance",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 127,
    name: "MSc International Financial Management (DDM International Financial Management)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-international-financial-management/",
  },
  {
    id: 128,
    name: "MSc Marketing",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/marketing/",
  },
  {
    id: 129,
    name: "MA/MSc Marketing (DDM Strategic Marketing Intelligence)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-strategic-marketing-intelligence/",
  },
  {
    id: 130,
    name: "MSc Marketing (DDM Marketing and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-marketing-finance/",
  },
  {
    id: 131,
    name: "MSc Marketing (DDM Chinese Economy and Finance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-chinese-economy-and-finance/",
  },
  {
    id: 132,
    name: "MSc Marketing (DDM Marketing Information Systems)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-marketing-information-systems/",
  },
  {
    id: 133,
    name: "MSc Marketing -Marketing Analytics and Data Science",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/msc-marketing-marketing-analytics-and-data-science/",
  },
  {
    id: 134,
    name: "MSc Marketing- Marketing Management",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/msc-marketing-marketing-management/",
  },
  {
    id: 135,
    name: "MSc Research Master in Economics and Business",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/research-master-in-economics-and-business/",
  },
  {
    id: 136,
    name: "MSc Supply Chain Management",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/supply-chain-management/",
  },
  {
    id: 137,
    name: "MSc Technology and Operations Management",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/technology-and-operations-management/",
  },
  {
    id: 138,
    name: "MSc Technology and Operations Management (DDM Operations Management)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-operations-management/",
  },
  {
    id: 139,
    name: "MSc Cultural Geography(Climate Adaptation governance)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/climate-adaptation-governance/",
  },
  {
    id: 140,
    name: "MSc Cultural Geography(Sustainable Tourism & society)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/sustainable-tourism-society/",
  },
  {
    id: 141,
    name: "MSc Sustainable Entrepreneurship",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/sustainable-entrepreneurship/",
  },
  {
    id: 142,
    name: "MSc Voice Technology",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/voice-technology/",
  },
  {
    id: 143,
    name: "MSc Behavioural and Cognitive Neurosciences(Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/behavioural-and-cognitive-neurosciences-research/",
  },
  {
    id: 144,
    name: "MSc Behavioural and Social Sciences (Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/behavioural-and-social-sciences-research/",
  },
  {
    id: 145,
    name: "MSc Biomedical Engineering ",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/biomedical-engineering/",
  },
  {
    id: 146,
    name: "MSc Biomedical Sciences ",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/biomedical-sciences/",
  },
  {
    id: 147,
    name: "MSc Biomolecular Sciences",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/biomolecular-sciences/",
  },
  {
    id: 148,
    name: "MSc Clinical and Psychosocial Epidemiology (Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/clinical-and-psychosocial-epidemiology-research/",
  },
  {
    id: 149,
    name: "MSc Clinical and Psychosocial Epidemiology: Health Systems and Prevention (Research)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/cpe-track-health-systems-and-prevention-research/",
  },
  {
    id: 150,
    name: "MSc Clinical Neuropsychology",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/clinical-neuropsychology/",
  },
  {
    id: 151,
    name: "MSc Ecology and Evolution ",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/ecology-and-evolution/",
  },
  {
    id: 152,
    name: "MSc Energy and Environmental Sciences ",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/energy-and-environmental-sciences/",
  },
  {
    id: 153,
    name: "MSc Human Movement Sciences ",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/human-movement-sciences/",
  },
  {
    id: 154,
    name: "MSc Molecular Medicine and Innovative Treatment (Research)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/molecular-medicine-and-innovative-treatment/",
  },
  {
    id: 155,
    name: "MSc Molecular Medicine and Innovative Treatment (Innovative Medicine)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/innovative-medicine/",
  },
  {
    id: 156,
    name: "MSc Medical Pharmaceutical Sciences",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/medical-pharmaceutical-sciences/",
  },
  {
    id: 157,
    name: "MSc Sport Sciences",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/sport-sciences/",
  },
  {
    id: 158,
    name: "LLM Energy and Climate Law",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/energy-and-climate-law/",
  },
  {
    id: 159,
    name: "MLB European Law in a Global Context",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/European-law-in-a-global-context/",
  },
  {
    id: 160,
    name: "LLM Technology Law and Innovation",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/technology-law-and-innovation/",
  },
  {
    id: 161,
    name: "LLM Global Criminal Law",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/global-criminal-law/",
  },
  {
    id: 162,
    name: "LLM Governance and Law in Digital Society ",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/governance-and-law-in-digital-society/",
  },
  {
    id: 163,
    name: "LLM International Commercial Law",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/international-commercial-law/",
  },
  {
    id: 164,
    name: "LLM International Human Rights Law",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/international-human-rights-law/",
  },
  {
    id: 165,
    name: "LLM Public International Law",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/public-international-law/",
  },
  {
    id: 166,
    name: "MA Philosophy ",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 16,000",
    url: "https://www.rug.nl/masters/philosophy/",
  },
  {
    id: 167,
    name: "MA Philosophy (Research)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 16,000",
    url: "https://www.rug.nl/masters/philosophy-research/",
  },
  {
    id: 168,
    name: "MSc Philosophy, Politics and Economics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 16,000",
    url: "https://www.rug.nl/masters/philosophy-politics-and-economics/",
  },
  {
    id: 169,
    name: "MA Philosophy, Science and Humanities",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 16,000",
    url: "https://www.rug.nl/masters/philosophy-science-and-humanities/",
  },
  {
    id: 170,
    name: "MSc Applied Mathematics ",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/applied-mathematics",
  },
  {
    id: 171,
    name: "MSc Applied Physics",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/applied-physics/",
  },
  {
    id: 172,
    name: "MSc Artificial Intelligence ",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/artificial-intelligence/",
  },
  {
    id: 173,
    name: "MSc Astronomy",
    school: "University of Groningen ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/astronomy/",
  },
  {
    id: 174,
    name: "MSc Behavioural and Cognitive Neurosciences (Research)",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/behavioural-and-cognitive-neurosciences-research/",
  },
  {
    id: 175,
    name: "MSc Biology ",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/biology/",
  },
  {
    id: 176,
    name: "MSc Biomedical Engineering ",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/biomedical-engineering/",
  },
  {
    id: 177,
    name: "MSc Biomolecular Sciences",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/biomolecular-sciences/",
  },
  {
    id: 178,
    name: "MSc Chemical Engineering ",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/chemical-engineering/",
  },
  {
    id: 179,
    name: "MSc Chemistry",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/chemistry/",
  },
  {
    id: 180,
    name: "MSc Computing Science",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/computing-science/",
  },
  {
    id: 181,
    name: "MSc Computational Cognitive Science",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/computational-cognitive-science/",
  },
  {
    id: 182,
    name: "MSc Energy and Environmental Sciences",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/energy-and-environmental-sciences/",
  },
  {
    id: 183,
    name: "MSc Industrial Engineering and Management",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/industrial-engineering-and-management/",
  },
  {
    id: 184,
    name: "MSc Marine Biology",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/marine-biology/",
  },
  {
    id: 185,
    name: "MSc Mathematics",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/mathematics/",
  },
  {
    id: 186,
    name: "MSc Science Education and Communication",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/science-education-and-communication",
  },
  {
    id: 187,
    name: "MSc Mechanical Engineering",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/mechanical-engineering/",
  },
  {
    id: 188,
    name: "MSc Molecular Medicine and Innovative Treatment (Research)",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/molecular-medicine-and-innovative-treatment/",
  },
  {
    id: 189,
    name: "MSc Nanoscience",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/nanoscience/",
  },
  {
    id: 190,
    name: "MSc Physics",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/physics/",
  },
  {
    id: 191,
    name: "MSc Systems & Control",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/systems-control/",
  },
  {
    id: 192,
    name: "MSc Water Technology (Joint Degree)",
    school: "University of Groningen",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 20,700",
    url: "https://www.rug.nl/masters/water-technology-joint-degree/",
  },
  {
    id: 193,
    name: "MSc Economic Geography ",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/economic-geography/",
  },
  {
    id: 194,
    name: "MSc Economic Geography (DDM International Programme in Economic Geography)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-international-programme-in-economic-geography/",
  },
  {
    id: 195,
    name: "MSc Economic Geography: Regional Competitiveness and Trade",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/economic-geography-regional-competitiveness-and-trade/",
  },
  {
    id: 196,
    name: "MSc Environmental and Infrastructure Planning",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/environmental-and-infrastructure-planning/",
  },
  {
    id: 197,
    name: "MSc Environmental and Infrastructure Planning (DDM Development Planning and Infrastructure Management)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-development-planning-and-infrastructure-management/",
  },
  {
    id: 198,
    name: "MSc Environmental and Infrastructure Planning (DDM Water and Coastal Management)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-water-and-coastal-management/",
  },
  {
    id: 199,
    name: "MSc Environmental and Infrastructure Planning (DDM Urban Governance within a Global Environment)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-urban-governance-within-a-global-environment/",
  },
  {
    id: 200,
    name: "MSc Environmental and Infrastructure Planning (DDM Urban Planning, Environment and Infrastructure)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/master/ddm-urban-planning-environment-and-infrastructure/",
  },
  {
    id: 201,
    name: "MSc Population Studies",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/population-studies/",
  },
  {
    id: 202,
    name: "MSc Population Studies (DDM Social Demography)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-social-demography/",
  },
  {
    id: 203,
    name: "MSc Population Studies (DDM Demography and Social Inequality ",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-demography-and-social-inequality/",
  },
  {
    id: 204,
    name: "MSc Real Estate Studies",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/real-estate-studies/",
  },
  {
    id: 205,
    name: "MSc Society, Sustainability and Planning ",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/society-sustainability-and-planning/",
  },
  {
    id: 206,
    name: "MSc Society, Sustainability and Planning (DDM Urban Planning, Society and Sustainability)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/ddm-urban-planning-society-and-sustainability/",
  },
  {
    id: 207,
    name: "MSc Spatial Sciences",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 17,800",
    url: "https://www.rug.nl/masters/spatial-sciences-research/",
  },
  {
    id: 208,
    name: "MSc Spatial Sciences: Islands and Sustainability (Erasmus Mundus)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/islands-and-sustainability/",
  },
  {
    id: 209,
    name: "MA Theology and Religious Studies",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/theology-religious-studies/",
  },
  {
    id: 210,
    name: "MA Theology and Religious Studies (Religion and Pluralism, Ancient and Modern)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/religion-pluralism-ancient-modern/",
  },
  {
    id: 211,
    name: "MA Theology and Religious Studies (Heritage and Religion)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/heritage-and-religion/",
  },
  {
    id: 212,
    name: "MA Theology and Religious Studies (Religion, Conflict and Globalisation)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/religion-conflict-and-globalisation/",
  },
  {
    id: 213,
    name: "MA Theology and Religious Studies (Research)",
    school: "University of Groningen ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/theology-religious-studies-research/",
  },
  {
    id: 214,
    name: "MA Theology and Religious Studies (Religious Diversity in a Globalised World-EM)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/religious-diversity-in-a-globalised-world-em-research/",
  },
  {
    id: 215,
    name: "MSc in Cultural Geography",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/sustainable-tourism-society/",
  },
  {
    id: 216,
    name: " MA in Linguistics",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/climate-adaptation-governance/",
  },
  {
    id: 217,
    name: "LLM in Law and Public Administration",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/governance-and-law-in-digital-society/#!requirements",
  },
  {
    id: 218,
    name: "MSc in Voice Technology",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/voice-technology/#!requirements",
  },
  {
    id: 219,
    name: "MSc in Water Technology (joint degree)",
    school: "University of Groningen",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.rug.nl/masters/water-technology-joint-degree/",
  },
  {
    id: 220,
    name: "MSc Software Engineering",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/software-engineering/software-engineering.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 221,
    name: "MSc Artificial Intelligence",
    school: "University of Amsterdam ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/artificial-intelligence/artificial-intelligence.html?origin=znSrDUT%2BQ5uz6dso72fBmw",
  },
  {
    id: 222,
    name: "MSc Computer Science ",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/shared-content/programmas/en/masters/computer-science/computer-science.html",
  },
  {
    id: 223,
    name: "MSc Security and Network Engineering ",
    school: "University of Amsterdam ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/shared-content/programmas/en/masters/security-and-network-engineering/security-and-network-engineering.html?origin=znSrDUT%2BQ5uz6dso72fBmw",
  },
  {
    id: 224,
    name: "LLM European Competition Law and Regulation (International and European Law)",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/international-and-european-law-european-competition-law-and-regulation/european-competition-law-and-regulation.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 225,
    name: "LLM European Private Law",
    school: "University of Amsterdam ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/european-private-law/european-private-law.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 226,
    name: "LLM European Union Law (International and European Law)",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "",
  },
  {
    id: 227,
    name: "LLM International and Transnational Criminal Law (International Criminal Law) ",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/international-and-transnational-criminal-law-llm/international-and-transnational-criminal-law.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 228,
    name: "LLM International Criminal Law- Joint Program with Columbia Law School (International Criminal Law)",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/international-criminal-law/international-criminal-law.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 229,
    name: "LLM International Tax Law (Advanced)",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/advanced-masters/international-tax-law/international-tax-law.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 230,
    name: "LLM International Trade and Investment Law (International and European Law)",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/international-and-european-law-international-trade-and-investment-law/international-trade-and-investment-law.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 231,
    name: "LLM Law and Finance",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/law--finance/law-and-finance.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 232,
    name: "LLM Public International Law (International and European Law)",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/programmes/masters/international-and-european-law-public-international-law/public-international-law.html?origin=5BOaRAofTjCccATraJp2XA",
  },
  {
    id: 233,
    name: "PhD Programme in Law",
    school: "University of Amsterdam ",
    country: "Netherlands",
    degree: "PhD",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uva.nl/en/about-the-uva/organisation/faculties/amsterdam-law-school/research/phd-research/phd.html",
  },
  {
    id: 234,
    name: "LLM Commercial and Company Law",
    school: "Erasmus University",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.eur.nl/en/master/commercial-and-company-law/",
  },
  {
    id: 235,
    name: "LLM International and European Union Law",
    school: "Erasmus University",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.eur.nl/en/master/international-and-european-union-law/",
  },
  {
    id: 236,
    name: "LLM International Arbitration ",
    school: "Erasmus University",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.eur.nl/en/master/international-arbitration/",
  },
  {
    id: 237,
    name: "LLM International Business Law ",
    school: "Erasmus University",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.eur.nl/en/master/international-business-law/",
  },
  {
    id: 238,
    name: "LLM Maritime and Transport Law",
    school: "Erasmus University",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.eur.nl/en/master/maritime-transport-law/",
  },
  {
    id: 239,
    name: "MSc Molecular Medicine ",
    school: "Erasmus University",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.eur.nl/en/research-master/molecular-medicine/",
  },
  {
    id: 240,
    name: "MSc Artificial Intelligence",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/artificial-intelligence/",
  },
  {
    id: 241,
    name: "MSc Bioinformatics and Biocomplexity ",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/bioinformatics-and-biocomplexity/",
  },
  {
    id: 242,
    name: "MSc Computing Science",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/computing-science/",
  },
  {
    id: 243,
    name: "MSc Data Science ",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/data-science/",
  },
  {
    id: 244,
    name: "MSc Human Computer Interaction",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/human-computer-interaction/",
  },
  {
    id: 245,
    name: "LLM Law and Economics ",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/law-and-economics/",
  },
  {
    id: 246,
    name: "LLM Law and Sustainability in Europe",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/law-and-sustainability-europe/",
  },
  {
    id: 247,
    name: "LLM Law and Technology in Europe ",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/law-and-technology-europe/",
  },
  {
    id: 248,
    name: "LLM Legal Research",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/legal-research/",
  },
  {
    id: 249,
    name: "LLM Public International Law",
    school: "Utrecht University ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.uu.nl/en/masters/public-international-law/",
  },
  {
    id: 250,
    name: "BSc Aerospace Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Bachelor's ",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/onderwijs/opleidingen/bachelors/aerospace-engineering/bsc-aerospace-engineering/",
  },
  {
    id: 251,
    name: "BSc Computer Science and Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Bachelor's ",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/bachelors/cse/bachelor-of-computer-science-and-engineering",
  },
  {
    id: 252,
    name: "MSc Aerospace Engineering",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/biomedical-engineering/msc-biomedical-engineering",
  },
  {
    id: 253,
    name: "MD (Doctor of Medicine)",
    school: "Poznan University of Medical Sciences",
    country: "Poland",
    degree: "Professional",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://pums.ump.edu.pl/admissions/medicine-program/medicine-admission-requirements.html",
  },
  {
    id: 254,
    name: "DDS (Doctor of Dentistry)",
    school: "Poznan University of Medical Sciences",
    country: "Poland",
    degree: "Professional",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://pums.ump.edu.pl/admissions/dentistry.html",
  },
  {
    id: 255,
    name: "MD (Doctor of Medicine)",
    school: "Medical University of Warsaw",
    country: "Poland",
    degree: "Professional",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://ed.wum.edu.pl/home/candidates/",
  },
  {
    id: 256,
    name: "DMD (Doctor of Dental Medicine)",
    school: "Medical University of Warsaw",
    country: "Poland",
    degree: "Professional",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://wls.wum.edu.pl/edd-candidates",
  },
  {
    id: 257,
    name: "PharmD",
    school: "Medical University of Warsaw",
    country: "Poland",
    degree: "Professional",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://wf.wum.edu.pl/pharmach-program",
  },
  {
    id: 258,
    name: "MSc Biomedical Engineering",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/biomedical-engineering/msc-biomedical-engineering",
  },
  {
    id: 259,
    name: "MSc Chemical Engineering",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/chemical-engineering/msc-chemical-engineering",
  },
  {
    id: 260,
    name: "MSc Civil Engineering",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/civil-engineering/msc-civil-engineering",
  },
  {
    id: 261,
    name: "MSc Complex Systems Engineeering and Management",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/cosem/msc-complex-systems-engineering-and-management",
  },
  {
    id: 262,
    name: "MSc Computer & Embedded Systems Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/msc-computer-embedded-systems-engineering",
  },
  {
    id: 263,
    name: "MSc Computer Science ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/cs/msc-computer-science",
  },
  {
    id: 264,
    name: "MSc Construction Management and Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/construction-management-and-engineering/msc-construction-management-and-engineering",
  },
  {
    id: 265,
    name: "MSc Electrical Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/electrical-engineering/msc-electrical-engineering",
  },
  {
    id: 266,
    name: "MSc Environmental Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/environmental-engineering/msc-environmental-engineering",
  },
  {
    id: 267,
    name: "MSc Materials Science and Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/materials-science-engineering/msc-materials-science-engineering",
  },
  {
    id: 268,
    name: "MSc Mechanical Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/mechanical-engineering/msc-mechanical-engineering",
  },
  {
    id: 269,
    name: "MSc Offshore & Dredging Engineering ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/offshore-dredging-engineering/msc-offshore-dredging-engineering",
  },
  {
    id: 270,
    name: "MSc Quantum Information Science and Technology ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/robotics/msc-robotics",
  },
  {
    id: 271,
    name: "MSc Sustainable Energy Technology ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/sustainable-energy-technology/msc-sustainable-energy-technology",
  },
  {
    id: 272,
    name: "MSc Systems and Control ",
    school: "Delft University of Technology ",
    country: "Netherlands ",
    degree: "Masters",
    duration: "2 years",
    tuition: "€ 19,600",
    url: "https://www.tudelft.nl/en/education/programmes/masters/systems-control/msc-systems-control",
  },
];

export default netherlandsData;
