// course data for United States
const usData = [
  {
    id: 1,
    name: "Advanced Manufacturing, Additive Manufacturing Track (M.ENG.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/advanced-manufacturing-additive-manufacturing-track-meng",
  },
  {
    id: 2,
    name: "Advanced Manufacturing, Automation and Control Systems Track (M.ENG.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/advanced-manufacturing-automation-and-control-systems-track-meng",
  },
  {
    id: 3,
    name: "Architectural Engineering(M.ENG.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/architectural-engineering-meng",
  },
  {
    id: 4,
    name: "Advanced Manufacturing, Digital Manufacturing Track (M.ENG.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/advanced-manufacturing-digital-manufacturing-track-meng",
  },
  {
    id: 5,
    name: "Architectural Engineering(M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/architectural-engineering-ms",
  },
  {
    id: 6,
    name: "Artificial Intelligence, Computer Vision, and Control (M.ENG.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/artificial-intelligence-computer-vision-and-control-meng",
  },
  {
    id: 7,
    name: "Autonomous Systems and Robotics (M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/autonomous-systems-and-robotics-ms",
  },
  {
    id: 8,
    name: "Biological Engineering(M.A.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/biological-engineering-mas",
  },
  {
    id: 9,
    name: "Biomedical Data Science and Modeling (M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/biomedical-data-science-and-modeling-ms",
  },
  {
    id: 10,
    name: "Biomedical Engineering(M.ENG.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/biomedical-engineering-mas",
  },
  {
    id: 11,
    name: "Biomedical Imaging and Signals (M.A.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/biomedical-imaging-and-signals-mas",
  },
  {
    id: 12,
    name: "Biomedical Engineering(M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/biomedical-engineering-ms",
  },
  {
    id: 13,
    name: "Chemical Engineering(M.A.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/chemical-engineering-mas",
  },
  {
    id: 14,
    name: "Chemical Engineering(M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/chemical-engineering-ms",
  },
  {
    id: 15,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/civil-engineering-ms",
  },
  {
    id: 16,
    name: "Computer Engineering(M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/computer-engineering-ms",
  },
  {
    id: 17,
    name: "Computational Engineering, Biomedicine Track(M.A.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/computational-engineering-biomedicine-track-mas",
  },
  {
    id: 18,
    name: "Computational Engineering, Computational Chemical Engineeering Track(M.A.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/computational-engineering-computational-chemical-engineering-track-mas",
  },
  {
    id: 19,
    name: "Applied Cybersecurity and Digital Forensics (M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/applied-cybersecurity-and-digital-forensics-ms",
  },
  {
    id: 20,
    name: "Applied Mathematics (M.A.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/applied-mathematics-mas",
  },
  {
    id: 21,
    name: "Applied Mathematics (M.S.)",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "https://www.iit.edu/academics/programs/applied-mathematics-ms",
  },
  {
    id: 22,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "",
  },
  {
    id: 23,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "",
  },
  {
    id: 24,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "",
  },
  {
    id: 25,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "",
  },
  {
    id: 26,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "",
  },
  {
    id: 27,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "",
  },
  {
    id: 28,
    name: "",
    school: "Illinois Institute of Technology",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$1,712 per Credit Hour",
    url: "",
  },
  {
    id: 29,
    name: "BSc Artificial Intelligence",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 83697",
    url: "https://www.cs.cmu.edu/bs-in-artificial-intelligence/",
  },
  {
    id: 30,
    name: "BSc Computational Biology",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 83697",
    url: "https://www.cmu.edu/admission/majors-programs/school-of-computer-science/computational-biology#computational-biology",
  },
  {
    id: 31,
    name: "BSc Computer Science",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 83697",
    url: "https://www.cmu.edu/admission/majors-programs/school-of-computer-science/computer-science#computer-science",
  },
  {
    id: 32,
    name: "BSc Human-Computer Interaction",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 83697",
    url: "https://www.cmu.edu/admission/majors-programs/school-of-computer-science/human-computer-interaction#human-computer-interaction",
  },
  {
    id: 33,
    name: "MSc Automated Science: Biological Experimentation (MSAS)",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 83697",
    url: "https://msas.cbd.cmu.edu/",
  },
  {
    id: 34,
    name: "MSc Computational Science",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 83697",
    url: "https://www.cmu.edu/ms-compbio/",
  },
  {
    id: 35,
    name: "MSc Computer Science",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 83697",
    url: "https://csd.cmu.edu/academics/masters/ms-in-computer-science",
  },
  {
    id: 36,
    name: "Masters of Educational Technology and Applied Learning Science.",
    school: "Carnegie Mellon University ",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://metals.hcii.cmu.edu",
  },
  {
    id: 37,
    name: "Masters of Computational Data Science",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "",
    url: "https://mcds.cs.cmu.edu/learn-us",
  },
  {
    id: 38,
    name: "MSc Artificial Intelligence and Innovation ",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://msaii.cs.cmu.edu",
  },
  {
    id: 39,
    name: "MSc Intelligent Information Systems ",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://miis.cs.cmu.edu/learn-us-overview",
  },
  {
    id: 40,
    name: "MSc Language Technologies ",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://lti.cs.cmu.edu/mlt/learn-us",
  },
  {
    id: 41,
    name: "MSc Machine Learning",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://www.ml.cmu.edu/academics/primary-ms-machine-learning-masters.html",
  },
  {
    id: 42,
    name: "MSc Master of Science- Computer Vision",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 55026.00",
    url: "https://www.ri.cmu.edu/education/academic-programs/master-of-science-computer-vision/",
  },
  {
    id: 43,
    name: "MSc Master of Science Robotics",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://www.ri.cmu.edu/education/academic-programs/master-of-science-robotics/",
  },
  {
    id: 44,
    name: "MSc Robotics Systems Development ",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 55578.00",
    url: "https://mrsd.ri.cmu.edu",
  },
  {
    id: 45,
    name: "MSc Privacy Engineering ",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://privacy.cs.cmu.edu",
  },
  {
    id: 46,
    name: "MSc Software Engineering ",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://mse.isri.cmu.edu/applicants/mse-as/index.html",
  },
  {
    id: 47,
    name: "MSc Software Engineering (Embedded Systems)",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://mse.isri.cmu.edu/applicants/mse-ap/index.html",
  },
  {
    id: 48,
    name: "MSc Software Engineering (Scalable Systems)",
    school: "Carnegie Mellon University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 85542.00",
    url: "https://mse.isri.cmu.edu/applicants/mse-ap/index.html",
  },
  {
    id: 49,
    name: "BSc Computer Engineering ",
    school: "Stevens Institute of Technology ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 81922.00",
    url: "https://www.stevens.edu/program/computer-engineering-bachelor-degree",
  },
  {
    id: 50,
    name: "BSc Computer Science",
    school: "Stevens Institute of Technology ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 81922.00",
    url: "https://www.stevens.edu/program/computer-science-bachelor-degree",
  },
  {
    id: 51,
    name: "BSc Cybersecurity ",
    school: "Stevens Institute of Technology ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 81922.00",
    url: "https://www.stevens.edu/program/cybersecurity-bachelor-degree",
  },
  {
    id: 52,
    name: "B.E Software Engineering ",
    school: "Stevens Institute of Technology ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 81922.00",
    url: "https://www.stevens.edu/school-of-systems-and-enterprises/undergraduate-programs/Software-Engineering",
  },
  {
    id: 53,
    name: "MSc Applied Artificial Intelligence",
    school: "Stevens Institute of Technology ",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 64228.00",
    url: "https://www.stevens.edu/program/applied-artificial-intelligence-masters",
  },
  {
    id: 54,
    name: "B.Comp.E Computer Engineering ",
    school: "University of Minnesota  ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 60356.00",
    url: "https://cse.umn.edu/cs",
  },
  {
    id: 55,
    name: "BSc Computer Science",
    school: "University of Minnesota  ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 60356.00",
    url: "https://majors.umn.edu/major/computer-science-bs",
  },
  {
    id: 56,
    name: "BSc Graphics Design",
    school: "University of Minnesota  ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 60356.00",
    url: "https://majors.umn.edu/major/graphic-design",
  },
  {
    id: 57,
    name: "BSc Management Information Systems",
    school: "University of Minnesota  ",
    country: "United States",
    degree: "Bachelors",
    duration: "2 years",
    tuition: "$ 60356.00",
    url: "https://majors.umn.edu/major/management-information-systems",
  },
  {
    id: 58,
    name: "MSc Computer Science",
    school: "University of Minnesota  ",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "",
    url: "",
  },
  {
    id: 59,
    name: "Master of Architecture (M.Arch)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 16180",
    url: "https://www.depts.ttu.edu/architecture/acad-admissions/graduate-degrees-march.php",
  },
  {
    id: 60,
    name: "Master of Science Architecture (M.S.Arch)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 16180",
    url: "https://www.depts.ttu.edu/architecture/acad-admissions/graduate-degrees-msarch.php",
  },
  {
    id: 61,
    name: "Bachelor of Science in Architecture (B.S.Arch)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 16180",
    url: "https://www.depts.ttu.edu/architecture/acad-admissions/undergraduate-degrees.php",
  },
  {
    id: 62,
    name: "Master of Science in Accounting (MSA)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 21180",
    url: "https://www.depts.ttu.edu/rawlsbusiness/graduate/ms/accounting/",
  },
  {
    id: 63,
    name: "Master of Science in Data Science (MSDS)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 21180",
    url: "https://www.depts.ttu.edu/rawlsbusiness/graduate/ms/datascience/",
  },
  {
    id: 64,
    name: "Master of Science in Finance (MS in Finance)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Masters",
    duration: "2 years",
    tuition: "$ 21180",
    url: "https://www.depts.ttu.edu/rawlsbusiness/graduate/ms/finance/",
  },
  {
    id: 65,
    name: "Master of Science in Marketing Research and Analytics (MSMRA)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Master",
    duration: "2 years",
    tuition: "$ 21180",
    url: "https://www.depts.ttu.edu/rawlsbusiness/graduate/ms/msmr/",
  },
  {
    id: 66,
    name: "Bachelor of Business Adminstration in Accounting (B.B.A)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 24452",
    url: "https://www.depts.ttu.edu/rawlsbusiness/about/usc/academics/explore/accounting/",
  },
  {
    id: 67,
    name: "Bachelor of Business Adminstration in Energy Commerce (Energy Commerce, B.B.A)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 24452",
    url: "https://www.depts.ttu.edu/rawlsbusiness/about/usc/academics/explore/energy-commerce/",
  },
  {
    id: 68,
    name: "Bachelor of Business Adminstration in Finance (B.B.A Finance)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 24452",
    url: "https://www.depts.ttu.edu/rawlsbusiness/about/usc/academics/explore/finance/",
  },
  {
    id: 69,
    name: "Bachelor of Business Adminstration in Information Technology (B.B.A)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 24452",
    url: "https://www.depts.ttu.edu/rawlsbusiness/about/usc/academics/explore/it/",
  },
  {
    id: 70,
    name: "Bachelor of Business Administration in Management (B.B.A)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 24452",
    url: "https://www.depts.ttu.edu/rawlsbusiness/about/usc/academics/explore/management/",
  },
  {
    id: 71,
    name: "Bachelor of Business Administration in Marketing (B.B.A)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 24452",
    url: "https://www.depts.ttu.edu/rawlsbusiness/about/usc/academics/explore/marketing/",
  },
  {
    id: 72,
    name: "Bachelor of Business Administration in Supply Chain Management (B.B.A)",
    school: "Texas Tech University",
    country: "United States",
    degree: "Bachelor",
    duration: "2 years",
    tuition: "$ 24452",
    url: "https://www.depts.ttu.edu/rawlsbusiness/about/usc/academics/explore/supply-chain/",
  },
];

export default usData;
